# Generated by Django 3.1.2 on 2020-10-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='id',
        ),
        migrations.AddField(
            model_name='developer',
            name='auto_increment_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
