# Generated by Django 3.1.2 on 2020-10-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201026_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=5)),
                ('developers', models.ManyToManyField(to='api.Developer')),
            ],
        ),
    ]
